# Generated by Django 3.1.6 on 2021-02-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
